apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-floweridentifier
  namespace: ml-serving
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: sklearn-runtime
      storageUri: s3://purushotham/serving/hello
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
